```{r set up, message=FALSE, warning=FALSE, include=FALSE, warnings=}

library(SparkR)
library(sparklyr)
library(DBI)
library(tidyverse)
library(dbplyr)
if (!require(afcharts)) install.packages(afcharts)
library(afcharts)
if (!require(openxlsx)) install.packages(openxlsx)
library(openxlsx)

con <- dbConnect(
  odbc::odbc(),
  dsn = 'Databricks',
  HTTPPath = 'sql/protocolv1/o/8723547585282153/0418-181355-5lqiplri',
  PWD = rstudioapi::askForPassword('Please enter Databricks PAT')
)

is.integer64 <- function(x) {class(x)=="integer64"}

round_f <- function(x) {
  ifelse(
    x < 10,
    0,
    10 * round(x/10)
    )}

round_ft <- function(x) {
  y <- round_f(x)
  ifelse(
    y ==0,
    "<10",
    format(y)
  )}

aftheme_mod <- function (base_size = 14, base_line_size = base_size/24, base_rect_size = base_size/24, 
    grid = c("y", "x", "xy", "none"), axis = c("x", "y", "xy", 
        "none"), ticks = c("xy", "x", "y", "none"), legend = c("right", 
        "left", "top", "bottom", "none")) 
{
    grid <- match.arg(grid)
    axis <- match.arg(axis)
    ticks <- match.arg(ticks)
    legend <- match.arg(legend)
    light_grey <- "#d9d9d9"
    afcharts_font <- "sans"
    half_line <- base_size/2
    grid_line <- ggplot2::element_line(colour = light_grey)
    grid_blank <- ggplot2::element_blank()
    grid_x <- if (grid %in% c("x", "xy")) 
        grid_line
    else grid_blank
    grid_y <- if (grid %in% c("y", "xy")) 
        grid_line
    else grid_blank
    axis_line <- ggplot2::element_line()
    axis_blank <- ggplot2::element_blank()
    axis_x <- if (axis %in% c("x", "xy")) 
        axis_line
    else axis_blank
    axis_y <- if (axis %in% c("y", "xy")) 
        axis_line
    else axis_blank
    axis_ticks <- ggplot2::element_line()
    no_ticks <- ggplot2::element_blank()
    ticks_x <- if (ticks %in% c("x", "xy")) 
        axis_ticks
    else no_ticks
    ticks_y <- if (ticks %in% c("y", "xy")) 
        axis_ticks
    else no_ticks
    ggplot2::theme(line = ggplot2::element_line(colour = light_grey, 
        size = base_line_size,  #linewidth = base_line_size, 
        linetype = 1, lineend = "butt"), 
        rect = ggplot2::element_rect(fill = "white", colour = "black", 
            #linewidth = base_rect_size, 
            size = base_rect_size, 
            linetype = 1), text = ggplot2::element_text(family = afcharts_font, 
            face = "plain", colour = "black", size = base_size, 
            lineheight = 0.9, hjust = 0.5, vjust = 0.5, angle = 0, 
            margin = ggplot2::margin(), debug = FALSE), axis.line = NULL, 
        axis.line.x = axis_x, axis.line.y = axis_y, axis.text = NULL, 
        axis.text.x = ggplot2::element_text(margin = ggplot2::margin(t = 0.8 * 
            half_line/2), vjust = 1), axis.text.x.top = ggplot2::element_text(margin = ggplot2::margin(b = 0.8 * 
            half_line/2), vjust = 0), axis.text.y = ggplot2::element_text(margin = ggplot2::margin(r = 0.8 * 
            half_line/2), hjust = 1), axis.text.y.right = ggplot2::element_text(margin = ggplot2::margin(l = 0.8 * 
            half_line/2), hjust = 0), axis.ticks = NULL, axis.ticks.x = ticks_x, 
        axis.ticks.y = ticks_y, axis.ticks.length = ggplot2::unit(half_line/2, 
            "pt"), axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = half_line/2), 
            vjust = 1), axis.title.x.top = ggplot2::element_text(margin = ggplot2::margin(b = half_line/2), 
            vjust = 0), axis.title.y = ggplot2::element_text(angle = 0, 
            margin = ggplot2::margin(r = half_line/2), vjust = 1, 
            hjust = 0.5), axis.title.y.right = ggplot2::element_text(angle = 0, 
            margin = ggplot2::margin(l = half_line/2), vjust = 1, 
            hjust = 0.5), legend.background = ggplot2::element_rect(colour = NA), 
        legend.spacing = ggplot2::unit(2 * half_line, "pt"), 
        legend.margin = ggplot2::margin(half_line, half_line, 
            half_line, half_line), legend.key = ggplot2::element_rect(fill = NA, 
            colour = NA), legend.key.size = ggplot2::unit(1.2, 
            "lines"), legend.text = ggplot2::element_text(size = ggplot2::rel(1)), 
        legend.text.align = NULL, legend.title = ggplot2::element_text(hjust = 0), 
        legend.title.align = NULL, legend.position = legend, 
        legend.direction = NULL, legend.justification = "centre", 
        legend.box = NULL, legend.box.margin = ggplot2::margin(0, 
            0, 0, 0, "cm"), legend.box.background = ggplot2::element_blank(), 
        legend.box.spacing = ggplot2::unit(2 * half_line, "pt"), 
        panel.background = ggplot2::element_blank(), panel.border = ggplot2::element_blank(), 
        panel.grid.major.x = grid_x, panel.grid.major.y = grid_y, 
        panel.grid.minor = ggplot2::element_blank(), panel.spacing = ggplot2::unit(half_line, 
            "pt"), panel.ontop = FALSE, strip.background = ggplot2::element_blank(), 
 #       strip.clip = "inherit", strip.text = ggplot2::element_text(margin = ggplot2::margin(0.8 * 
#            half_line, 0.8 * half_line, 0.8 * half_line, 0.8 * 
#            half_line)), strip.text.y = ggplot2::element_text(angle = -90), 
        strip.text.y.left = ggplot2::element_text(angle = 90), 
        strip.placement = "inside", strip.switch.pad.grid = ggplot2::unit(half_line/2, 
            "pt"), strip.switch.pad.wrap = ggplot2::unit(half_line/2, 
            "pt"), plot.background = ggplot2::element_rect(colour = "white"), 
        plot.title = ggplot2::element_text(size = ggplot2::rel(1.6), 
            hjust = 0, vjust = 1, margin = ggplot2::margin(b = half_line * 
                2)), plot.title.position = "panel", plot.subtitle = ggplot2::element_text(hjust = 0, 
            vjust = 1, margin = ggplot2::margin(b = half_line * 
                2)), plot.caption = ggplot2::element_text(size = ggplot2::rel(1), 
            hjust = 0, vjust = 1, margin = ggplot2::margin(t = half_line)), 
        plot.caption.position = "panel", plot.tag = ggplot2::element_text(size = ggplot2::rel(1.2), 
            hjust = 0.5, vjust = 0.5), plot.tag.position = "topleft", 
        plot.margin = ggplot2::margin(half_line, half_line, half_line, 
            half_line), complete = TRUE)}

```

```{r activity_data, echo=FALSE}

load_lu <- function(f) {
  assign(
    x = str_remove(f, ".csv"), 
    value = read.csv(
      paste0("~/collab/peolc/peolc_csds_project/input/", f),
      header = FALSE) %>%
      data.table::setnames(new = c("code", "text")),
    pos = .GlobalEnv)
  return(TRUE)
}

map(list.files("~/collab/peolc/peolc_csds_project/input/", pattern = "lu_"), load_lu)

ref_summary <- tbl(con, sql("
   SELECT DISTINCT
    Pseudo_Unique_ServiceRequestID,
    CASE
      WHEN Pseudo_PrimaryReferralReason = '026'
          OR Pseudo_ReferralReason_Other LIKE '%026%'
          OR TeamType = 14 THEN 1
      ELSE 0 END AS eol_referral
  FROM dsa_484452_h8s1l_collab.peolc_csds_ref"))

activity <- tbl(con, sql("
  SELECT *, 
    CASE 
      WHEN AttendanceStatus IN ('2','3','4','7') THEN 'N'
      WHEN AttendanceStatus IN  ('5','6') THEN 'Y'
      WHEN AttendanceStatus IS NULL OR AttendanceStatus = '' THEN 'B'
      ELSE 'I'
      END AS attendance_seen
  FROM hive_metastore.dsa_484452_h8s1l_collab.peolc_csds_act"))

seen <- c(
  "Y" = "Seen",  
  "N" = "Not seen",
  "B" = "No data",
  "I" = "Invalid data")

days <- c("<-1", "-1", "0", "1-7", ">7", "NK")

place_attendance_summary <- activity %>% 
  filter(yod==2024) %>%
  mutate(
    days = case_when(
      is.na(days_bf_eol) ~ 'NK',
      days_bf_eol < -1 ~ '<-1',
      days_bf_eol == -1 ~ '-1',
      days_bf_eol == 0 ~ '0',
      between(days_bf_eol,1,7) ~ '1-7',
      T ~ '>7'  )) %>%
  group_by(attendance_seen, Activity_LocationType, days) %>% 
  summarise(n=n()) %>% 
  collect() %>%
  mutate(
    n=as.integer(n),
    attendance_seen = factor(
      attendance_seen, 
      levels = names(seen), 
      labels = as.character(seen)),
    days = factor(days, levels = days, labels = days)) 

place_attendance_summary_tables <- map(
  c(count="n", pc = "pc_place"),
  function(x) {
  place_attendance_summary %>%
  group_by(Activity_LocationType, attendance_seen) %>%
  summarise( n = sum(n)) %>%
  group_by(Activity_LocationType) %>%    
  mutate(
    total_place = sum(n), 
    pc_place =100*n/total_place) %>%
      pivot_wider(
        id_cols = c(Activity_LocationType, total_place),
        names_from = attendance_seen, 
        values_from = {{x}}) %>%
      arrange(Activity_LocationType) %>%
      select(sort(names(.))) %>%
    relocate( Activity_LocationType, total_place) 
  })

days_attendance_summary_table <-map(
  c(count="n", pc = "pc_place"),
  function(x) {
  place_attendance_summary %>%  
  group_by(attendance_seen, days) %>%
  summarise(n=sum(n)) %>%
  group_by(days) %>%    
  mutate(
    total_days = sum(n), 
    pc_place =100*n/total_days) %>%
      pivot_wider(
        id_cols = c(days, total_days),
        names_from = attendance_seen, 
        values_from = {{x}}) %>%
      arrange(days) 
    #%>%
    #  select(sort(names(.))) %>%
    #relocate( Activity_LocationType, total_place) 
  })
  
activity2 <- activity %>%
  filter(!attendance_seen == "N") %>%
  left_join(ref_summary) %>%
  mutate(
    days_bf_eol = case_when(
      between(days_bf_eol, 0,7) ~ "0-7",
      between(days_bf_eol, 8,14) ~ "8-14",
      between(days_bf_eol, 15,30) ~ "15-30",
      between(days_bf_eol, 31,60) ~ "31-60",
      between(days_bf_eol, 61,90) ~ "61-90",
      days_bf_eol > 90 ~ "90",
      TRUE ~ "NA")) %>%
  group_by(
    AdminCategory,
    Activity_Type,
    Activity_LocationType,
    yod,
    eol_referral,
    days_bf_eol) %>%
  summarise(n=n()) %>%
  collect() %>%
  mutate(n=as.integer(n))

chartdata <- activity2 %>%
  group_by(Activity_Type, eol_referral, days_bf_eol) %>%
  summarise(n = sum(n)) %>%
  mutate(activitytype = as.integer(Activity_Type)) %>%
  left_join(lu_activitytype, by = c("activitytype"= "code")) %>%
  group_by(text, eol_referral, days_bf_eol) %>%
  summarise(n = sum(n)) %>%
  arrange(text, days_bf_eol) 

act_chart <-  map(c(eol=1, non_eol=0),function(x) {
  chartdata %>%
    filter(eol_referral == x) %>%
    ggplot(aes(y=text,x=n)) +
      geom_col()+
      facet_wrap(~days_bf_eol)
})

```






 