```{r set up, message=FALSE, warning=FALSE, include=FALSE}

library(SparkR)
library(sparklyr)
library(DBI)
library(tidyverse)
library(dbplyr)
if(!require(PHEindicatormethods)) install.packages("PHEindicatormethods", repos = "https://packages.sde.digital.nhs.uk/repository/cran-mirror/", dependencies = TRUE)
library(PHEindicatormethods)
if (!require(afcharts)) install.packages('afcharts')
library(afcharts)
if (!require(openxlsx)) install.packages('openxlsx')
library(openxlsx)
library(afcharts)

con <- dbConnect(
  odbc::odbc(),
  dsn = 'Databricks',
  HTTPPath = 'sql/protocolv1/o/8723547585282153/1007-063142-dtxq2zhk',
  PWD = rstudioapi::askForPassword('Please enter Databricks PAT')
)

is.integer64 <- function(x) {class(x)=="integer64"}

round_f <- function(x) {
  ifelse(
    x < 10,
    0,
    10 * round(x/10)
    )}

round_ft <- function(x) {
  y <- round_f(x)
  ifelse(
    y ==0,
    "<10",
    format(y)
  )}
```

```{r activity,ECHO = FALSE}

data_activity <- tbl(con, sql("
SELECT DISTINCT 
ref.PERSON_ID_DEID, ref.Pseudo_Unique_ServiceRequestID,act.Contact_Date, act.Consultation_Type, act.CareContact_Subject, act.Procedure_Scheme, act.CodedProcedure, act.Finding_Scheme, act.CodedFinding, act.Observation_Scheme, act.CodedObservation, act.ObservationValue,
CASE 
        WHEN ref.Pseudo_PrimaryReferralReason = '026'
            OR ref.Pseudo_ReferralReason_Other LIKE '%026%'
            OR ref.TeamType IN (14, 47) THEN 1    -- EOL referral
        ELSE 0                                -- referral, not EOL
        END AS eol_ref
FROM
dsa_484452_h8s1l_collab.peolc_csds_act AS act
INNER JOIN dsa_484452_h8s1l_collab.peolc_csds_ref AS ref
ON act.Person_ID_DEID = ref.Person_ID_DEID
AND act.Pseudo_Unique_ServiceRequestID = ref.Pseudo_Unique_ServiceRequestID
WHERE ref.yod=2024
"))

act_procedure_summary <- data_activity %>% 
  select(PERSON_ID_DEID, 
         Pseudo_Unique_ServiceRequestID, 
         Contact_Date,
         Procedure_Scheme, 
         CodedProcedure,
         eol_ref) %>%
  distinct() %>%
  collect() %>%
  group_by(Procedure_Scheme, 
         CodedProcedure,
         eol_ref) %>%
  summarise(n = n()) %>%
  arrange(desc(n))
  
act_finding_summary <- data_activity %>% 
  select(PERSON_ID_DEID, 
         Pseudo_Unique_ServiceRequestID, 
         Contact_Date,
         Finding_Scheme, CodedFinding,
         eol_ref) %>%
  distinct() %>%
  collect() %>%
  group_by(Finding_Scheme, CodedFinding,,
         eol_ref) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

  
act_finding_summary <- data_activity %>% 
  select(PERSON_ID_DEID, 
         Pseudo_Unique_ServiceRequestID, 
         Contact_Date,
         Finding_Scheme, CodedFinding,
         eol_ref) %>%
  distinct() %>%
  collect() %>%
  group_by(Finding_Scheme, CodedFinding,,
         eol_ref) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

``` 